const DESKTOP_MOTION = Object.freeze({
  enableScrollMotion: true,
  sectionMinHeight: '180vh',
  takeoverDistance: 18,
  surfaceTakeoverDistance: 100,
  surfaceHeight: '180vh',
  takeoverStart: 'top bottom',
  takeoverEnd: 'top 62%',
  titleRevealAt: 0.18,
  surfaceColor: '#020108',
  footerExitSurfaceTravel: -2.1,
  mainStageStart: 'top top',
  mainStageEnd: 'bottom bottom',
  mainStageTravel: -0.16,
  footerExitStageTravel: -0.62,
  footerExitLinksAt: 0.46,
  footerExitLinksClipDuration: 0.52,
  footerExitLinksCounterTravel: 0.75,
  footerExitTitleAt: 0.18,
  footerExitTitleClipDuration: 0.45,
  footerHeight: '100vh',
  footerParallaxStart: 'bottom bottom',
  footerParallaxEnd: 'bottom 35%',
  footerParallaxFrom: -18,
  footerParallaxTo: 0,
  footerSceneFrom: 12,
  footerSceneTo: 0,
  titleStartX: '110vw',
  titleAt: 0.18,
  titleDuration: 0.55,
  pairAt: 0.22,
  pairDuration: 0.65,
  secondPairOffset: 0.07,
  frameTravel: Object.freeze({ first: Object.freeze([1.1, -1.4]), second: Object.freeze([1.3, -1.4]) }),
  copyTravel: Object.freeze({ first: Object.freeze([1.1, -1.65]), second: Object.freeze([1.1, -1.4]) }),
  imageTravel: Object.freeze([-30, 30]),
});

const REDUCED_MOTION = Object.freeze({
  enableScrollMotion: false,
  sectionMinHeight: 'auto',
  takeoverDistance: 0,
  surfaceTakeoverDistance: 0,
  surfaceHeight: 'auto',
  takeoverStart: null,
  takeoverEnd: null,
  titleRevealAt: 0,
  surfaceColor: '#020108',
  footerExitSurfaceTravel: 0,
  mainStageStart: null,
  mainStageEnd: null,
  mainStageTravel: 0,
  footerExitStageTravel: 0,
  footerExitLinksAt: 0,
  footerExitLinksClipDuration: 0,
  footerExitLinksCounterTravel: 0,
  footerExitTitleAt: 0,
  footerExitTitleClipDuration: 0,
  footerHeight: 'auto',
  footerParallaxStart: null,
  footerParallaxEnd: null,
  footerParallaxFrom: 0,
  footerParallaxTo: 0,
  footerSceneFrom: 0,
  footerSceneTo: 0,
  titleStartX: 0,
  titleAt: 0,
  titleDuration: 0,
  pairAt: 0,
  pairDuration: 0,
  secondPairOffset: 0,
  frameTravel: Object.freeze({ first: Object.freeze([0, 0]), second: Object.freeze([0, 0]) }),
  copyTravel: Object.freeze({ first: Object.freeze([0, 0]), second: Object.freeze([0, 0]) }),
  imageTravel: Object.freeze([0, 0]),
});

export const getCinematicContactMotion = (reducedMotion) => (
  reducedMotion ? REDUCED_MOTION : DESKTOP_MOTION
);
